# =====================================================
# Basic Site Settings
# =====================================================
locale                   : "en-US"
title                    : "Americo's Page"
title_separator          : "-"
name                     : &name "Americo Cunha Jr"
description              : &description "Professor of Applied Mathematics and Engineering, Researcher in Nonlinear Systems"
url                      : "https://americocunhajr.github.io"
baseurl                  : "" # Keep blank if deploying on GitHub Pages at username.github.io
repository               : "americocunhajr/academicpages.github.io" # Your GitHub repository

# =====================================================
# Site Author - Sidebar Information
# =====================================================
author:
  avatar           : "americo.png"  # Profile image filename in /images/
  name             : "Americo Cunha Jr"
  bio              : "I deal with nonlinear systems."
  employer         : 
  email            : 

  # Academic Profiles
  googlescholar    : "https://scholar.google.com/citations?user=4r36RpoAAAAJ&hl=en"
  orcid            : #"https://orcid.org/0000-0002-8342-0363"
  researchgate     : "https://www.researchgate.net/profile/Americo-Cunha-Jr"
  scopus           : #"https://www.scopus.com/authid/detail.uri?authorId=56068096100"
  semantic         : #"https://www.semanticscholar.org/author/Americo-Cunha/47058383"
  webofscience     : #"https://www.webofscience.com/wos/author/record/1767361"
  lattes           : "http://lattes.cnpq.br/5659403706694491"


  # Repositories
  github           : "americocunhajr"

  # Social Media
  medium           : #"https://medium.com/@americocunhajr"
  linkedin         : "americocunhajr"
  youtube          : "americocunhajr"

# =====================================================
# Publication Categories
# =====================================================
publication_category:
  books:
    title: 'Books'
  bookchapters:
    title: 'Book Chapters'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'
  preprints:
    title: 'Preprints'

# =====================================================
# SEO & Analytics
# =====================================================
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
og_image                 : "images/og-image.png" # Default OpenGraph image

# Google Analytics (Optional)
analytics:
  provider               : "google-analytics-4"
  google:
    tracking_id          : "G-XXXXXXX" # Replace with your Google Analytics ID

# =====================================================
# Site Settings
# =====================================================
breadcrumbs              : true
words_per_minute         : 180
read_more                : "enabled"
talkmap_link             : false

# Comments (Optional)
comments:
  provider               : false 

# Atom/RSS Feed
atom_feed:
  hide                   : false
  path                   : feed.xml

# =====================================================
# Reading & Conversion Settings
# =====================================================
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Gemfile
  - LICENSE
  - node_modules
  - README
  - tmp
  - vendor

keep_files:
  - .git

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# =====================================================
# Collections (Publications, Teaching, Portfolio, Talks)
# =====================================================
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  software:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/

# Page Layout Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: software
    values:
      layout: single
      author_profile: true
      share: true

# =====================================================
# Styling & Performance
# =====================================================
sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC

# =====================================================
# Plugins
# =====================================================
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# =====================================================
# Archives
# =====================================================
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

# =====================================================
# Taxonomies
# =====================================================
#taxonomies:
#  category: "categories"
#  tag: "tags"
#  software: "software"
